python main.py \
--train_list "/home/users/nus/e1342275/scratch/v2_simulated_data_Switchboard_SRE_small_16k/data/simu3/data/all_files/all_simtrain.json" \
--eval_list "/home/users/nus/e1342275/scratch/datasets_tsvad/DIHARD 3/third_dihard_challenge_eval/data/ts_eval.json" \
--train_path "/home/users/nus/e1342275/scratch/v2_simulated_data_Switchboard_SRE_small_16k/data/simu3/data/all_files" \
--eval_path "/home/users/nus/e1342275/scratch/datasets_tsvad/DIHARD 3/third_dihard_challenge_eval/data" \
--musan_path "/home/users/nus/e1342275/scratch/datasets_tsvad/musan" \
--rir_path "/home/users/nus/e1342275/scratch/datasets_tsvad/RIRS_NOISES/simulated_rirs" \
--save_path "/home/users/nus/e1342275/scratch/simtrain_ecapa_wavLarge" \
--max_speaker 8 \
--warm_up_epoch 10 \
--batch_size 40 \
--rs_len 4 \
--test_shift 4 \
--lr 0.0001 \
--test_step 1 \
--max_epoch 40 \
--train \
--simtrain True
