python main.py \
--train_list "/home/users/nus/e1342275/scratch/datasets_tsvad/DIHARD 3/third_dihard_challenge_dev/data/ts_dev.json" \
--eval_list "/home/users/nus/e1342275/scratch/datasets_tsvad/DIHARD 3/third_dihard_challenge_eval/data/ts_eval.json" \
--train_path "/home/users/nus/e1342275/scratch/datasets_tsvad/DIHARD 3/third_dihard_challenge_dev/data" \
--eval_path "/home/users/nus/e1342275/scratch/datasets_tsvad/DIHARD 3/third_dihard_challenge_eval/data" \
--musan_path "/home/users/nus/e1342275/scratch/datasets_tsvad/musan" \
--rir_path "/home/users/nus/e1342275/scratch/datasets_tsvad/RIRS_NOISES/simulated_rirs" \
--save_path "/home/users/nus/e1342275/scratch/cross_attn_basic_ecapa_8" \
--max_speaker 8 \
--warm_up_epoch 5 \
--batch_size 40 \
--rs_len 4 \
--test_shift 4 \
--lr 0.0001 \
--lr_decay 0.95 \
--test_step 1 \
--max_epoch 60 \
--train